# Generated by Django 4.1.4 on 2023-02-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BR', 'Biryani'), ('MM', 'Momo'), ('CM', 'Chowmein'), ('DR', 'Drinks'), ('BU', 'Burger'), ('PZ', 'Pizza'), ('FS', 'Fish'), ('FR', 'Fries'), ('NA', 'NewArrivals')], max_length=2),
        ),
    ]
