# Generated by Django 4.1.4 on 2023-03-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way')], default='Pending', max_length=50),
        ),
    ]
